### ISSUE TITLE
📂 No folder /website/4_0_1 in repository, but it is in the release

### ISSUE THREAD

**Issue by Agzam4** [johnnesky/beepbox#34]
There is a folder in the  [release v4.0.1](https://github.com/johnnesky/beepbox/releases/tag/v4.0.1)
But this folder is missing in the repository ([main/website](https://github.com/johnnesky/beepbox/tree/main/website))

**Comment by johnnesky** [comment]
Yes, the latest version of BeepBox should be compiled directly from the TypeScript (.ts) source code. I only included the JavaScript (.js) for the old versions that are not based on the latest source code, since I do not plan on changing the old versions any more. The project has a README that explains how to compile.

The project copies of /website/3_0/ and /website/2_3/ because these can still be used at beepbox.co/3_0/ and beepbox.co/2_3/ but the latest version is just at beepbox.co/ and the .js files for the latest version are generated when you compile.

**Comment by johnnesky** [comment]
Also, if you want to try other versions, see the downloads in Releases:
https://github.com/johnnesky/beepbox/releases
