### ISSUE TITLE
Adding a new instrument type

### ISSUE THREAD

**Issue by meherranjan** [johnnesky/beepbox#43]
I checked EditorConfig.ts and noticed every instrument has some settings and I guess that is how the sounds are created(?). Is there a way I can find easily find the setting for the instrument, Harmonium?

**Comment by johnnesky** [comment]
Hi! Yes, that file contains the instrument settings for all of the preset instruments. (The actual process of converting those settings into sound waves mostly happens in synth.ts.) There currently isn't any preset for a harmonium, although it's similar to an accordion.

BeepBox has an undocumented keyboard shortcut, Shift+I, that copies the current instrument's settings into your computer's copy clipboard as JSON data. This data can be pasted into EditorConfig.ts (along with some metadata like the preset name and which MIDI instrument to use when exporting to MIDI) in order to create new presets. If I were to add a harmonium here, I'd probably add it to the "Bellows Instruments" section, although it and some other instruments in this section could also be considered reed instruments.

**Comment by meherranjan** [comment]
Thank John, that was really helpful. With some tweak I think I will be able to get the timbre/tone quality of Harmonium. 

One quick last question, where is the MAX settings for importing a sequence that has more than 128 notes defined in the application. I am trying to import a JSON that has around ~800 sequence notes.
