### ISSUE TITLE
feature: change octave for pc keyboard input

### ISSUE THREAD

**Issue by runlow** [johnnesky/beepbox#51]
When pressing capslock or recording I can't seem to find a way to input very high and very low notes other than transposing once entered.

**Comment by johnnesky** [comment]
Hi! There's an undocumented (sorry) feature where the available range of notes for performing is based on the octave scroll bar. Depending on your layout and zoom preferences, you might not otherwise be using the octave scroll bar, but if you zoom in (such that three octaves are visible at once) and move the scroll bar where you want, it'll continue using that range for performed notes in that channel even if you zoom out again. Does that help?

**Comment by runlow** [comment]
That's nice that it exists. It does help. Just tested it and it works as you described. Had the view fully zoomed out on fullscreen - maybe that's why I didn't notice this feature.

Maybe mentioning this in "Set up Note Recording..." and/or giving octave change a keyboard shortcut so it's not tied to zooming is a way to go?

The fact that there's a way to adjust it is cool either way, thank you.

**Comment by johnnesky** [comment]
I updated the note recording prompt to mention the octave scrollbar in: https://github.com/johnnesky/beepbox/commit/8618cad1950c67d13fb7426ed40761eb02c0cfdf
