### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Naether** [johnnesky/beepbox#8]
This isn't a issue, but a request.
### Could you make an Android version? ###
BeepBox on mobile is very laggy and one note play various notes at a time. If you cant fix this you could make an Android version.

**Comment by johnnesky** [comment]
Hi!

It won't help lag, but you can put BeepBox on your phone's home screen! Open the "vertical ellipsis" menu, aka the "kebab" menu in the top right corner of chrome while looking at BeepBox, and find the "Add to Home Screen" option. You can even use BeepBox offline!

What do you mean by "one note play various notes at a time"? 

I will be trying to reduce lag soon, but I can't make any promises!

**Comment by StinkerB06** [comment]
I think you should try Firefox for Android. BeepBox constantly stutters on Chrome, and on Firefox it doesn't stutter very often. This is based on what I perceived from _my_ phone though.

I'm not a Firefox fanboy in general due to being used to Chrome, so I'm not sure how adding webpages to the homescreen is done with the former. It could be done easily with the latter like he said, but I still wouldn't recommend using it for BeepBox.

**Comment by Naether** [comment]
Thanks, im currently on PC so i will test it later.

**Comment by Naether** [comment]
The add-beepbox-to-home-bar method didn't work. When i tap on it, it just
sends me back to chrome. Maybe is because it doesnt put the actual beepbox,
but the beepbox.co/#8bdh810...

**Comment by johnnesky** [comment]
Hi, sorry I wasn't clear. Yes, it brings you back to Chrome. However, as I said, this should still work if you're offline, even inside of Chrome.

I could have set it up so that it doesn't bring you back to Chrome, and instead opens as a separate app. This is known as a "progressive web app". As a side effect, that would get also rid of the address bar at the top, and the ability to have multiple BeepBox tabs open. However, losing the ability to have multiple BeepBox tabs open is enough of a degradation in user experience that I decided it wasn't worth it to use that feature.

**Comment by Naether** [comment]
Also, what if you could do things like this on beepbox
[image: Sin título.png]

**Comment by johnnesky** [comment]
Hmm, I don't think your image attachment is visible on GitHub.
