### ISSUE TITLE
problem: why is it called "note size"?

### ISSUE THREAD

**Issue by M0ahgra** [johnnesky/beepbox#84]
why is the envelope option called "note size" and not "note volume", is this a mistake?

**Comment by johnnesky** [comment]
No, that's intentional, although I can see why it might be confusing since "note size" is most often used to control "note volume", to the point where they may be so strongly associated that they might be considered the same thing.

"Note size" specifically refers to the visual thickness of the notes in the pattern editor, which you can edit by dragging vertically from above or below the note. By default, this note size controls the note's volume. However, you can add an envelope that makes note size control something else, and if you do, then note size stops controlling note volume. If you specifically want note size to control both note volume and something else at the same time, you need to add another envelope that links note size to note volume, otherwise it will only control one thing at a time.
